### ISSUE TITLE
Insert on-page TOC

### ISSUE THREAD

**Issue by ozh** [YOURLS/docs#27]
Would be nice to have a little TOC on top of each page as previously. Some pages are quite lengthy, this would help navigation and have a quick grasp of the page content

![image](https://user-images.githubusercontent.com/223647/164724868-f9a3d681-c046-4083-b4c8-ead260b702fd.png)

**Comment by LeoColomb** [comment]
As mentioned on my VuePress PR (https://github.com/YOURLS/docs/pull/24#issue-1209567230):

> Side note: the left sidebar is going to include headers at the 3rd level with the next vuepress release, an this will correctly replace the missing vitepress right sidebar.
